# action.yml
name: 'Hugo to Medium'
description: 'Pushes your blog from hugo to medium' 
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.blog-dir }}
branding:
  icon: 'aperture'
  color: 'gray-dark'
